### ISSUE TITLE
Websocket stops receiving messages

### ISSUE THREAD

**Issue by dasalz1** [polygon-io/issues#11]
**Client**
Which WebScoket client are using?
Python
**Issue**
A clear and concise description of the issue.
Socket stops collecting messages after some duration of time, not consistent sometimes 20 minutes sometimes an hour
**Expected Result**
Expected to receive messages uninterrupted while the socket is open
**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS and linus

**Comment by quantic-cloud** [comment]
Websocket connections can close unexpectedly. You code needs to be able to detect `close` messages, close your websocket connection and reconnect. Websockets libraries implement this differently, and it is not always explicit. What library are you using?

**Comment by dasalz1** [comment]
I'm using the "client-python" and it's setup almost exactly how the example on the main page has it, is the close message specific to the channel, such that I need to re-subscribe to that channel or the entire websocket client and I need to re-run my code for initializing and subscribing to all channels on that websocketclient. Thanks

**Comment by jrbell19** [comment]
Usually when messages stop coming through it means the data isn’t being consumed fast enough. There is a server side buffer and if it fills the connection will be killed. The best way to mitigate this is to read the packets off the network and immediately put them into a queue. Have a separate thread which is parsing the messages and running any logic on them.

**Comment by meyergin** [comment]
the same problem occurs.
I've tested to just read raw messages in a seperate thread, and connection is still kicked off(subscribe trade and quote of SP500 codes).
BTW, when I switch to ws(the test url) instead of wss, it seem work well.

**Comment by edzme** [comment]
Same issue here -- thought maybe it had to do with inactivity so I modified [this](https://github.com/websocket-client/websocket-client/blob/2222f2c49d71afd74fcda486e3dfd14399e647af/websocket/_app.py#L178) to do a 10 min ping/pong but didn't seem to help.

**Comment by jrbell19** [comment]
The websocket disconnect issue has been addressed. You should not experience this anymore. 

Apologies for the troubles.

**Comment by mbwmbw1337** [comment]
This issue is back for the crypto WebSocket API. No issues on forex... Would you be able to address @jrbell19?
